[package]
name = "rust-markdownlint-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "rust-markdownlint"
path = "src/main.rs"

[dependencies]
rust-markdownlint.workspace = true
anyhow.workspace = true
globset.workspace = true
ignore.workspace = true
rayon.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true
insta.workspace = true
